spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permissions_app?useSSL=false&serverTimezone=UTC
    username: myuser
    password: myuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false


logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
